# Generated by Django 2.2.5 on 2019-09-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hash',
        ),
        migrations.AddField(
            model_name='users',
            name='salt',
            field=models.CharField(default='spacecowboy', max_length=40),
        ),
    ]
